import 'package:banglabeats/core/app_export.dart';import 'package:banglabeats/presentation/history_music_page/history_music_page.dart';import 'package:banglabeats/presentation/history_podcast_page/history_podcast_page.dart';import 'package:banglabeats/widgets/app_bar/appbar_image.dart';import 'package:banglabeats/widgets/app_bar/appbar_title.dart';import 'package:banglabeats/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class HistoryPodcastTabContainerScreen extends StatefulWidget {@override _HistoryPodcastTabContainerScreenState createState() =>  _HistoryPodcastTabContainerScreenState();
onTapArrowleft23(BuildContext context) { Navigator.pop(context); } 
 }

// ignore_for_file: must_be_immutable
class _HistoryPodcastTabContainerScreenState extends State<HistoryPodcastTabContainerScreen> with  TickerProviderStateMixin {late TabController group44Controller;

@override void initState() { super.initState(); group44Controller = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(52), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24, top: 10, bottom: 14), onTap: () {onTapArrowleft23(context);}), title: AppbarTitle(text: "History", margin: getMargin(left: 16)), actions: [AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgSearch, margin: getMargin(left: 24, top: 10, right: 14)), AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgClock28x28, margin: getMargin(left: 20, top: 10, right: 38))]), body: Container(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(39), width: double.maxFinite, margin: getMargin(top: 29), child: TabBar(controller: group44Controller, labelColor: ColorConstant.redA70002, labelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), unselectedLabelColor: ColorConstant.gray500, unselectedLabelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), indicatorColor: ColorConstant.redA70002, tabs: [Tab(child: Text("Songs", overflow: TextOverflow.ellipsis)), Tab(child: Text("Podcasts", overflow: TextOverflow.ellipsis))])), Container(height: getVerticalSize(761), child: TabBarView(controller: group44Controller, children: [HistoryMusicPage(), HistoryPodcastPage()]))])))); } 
onTapArrowleft23(BuildContext context) { Navigator.pop(context); } 
 }
