name: banglabeats
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  cached_network_image: ^3.2.1
  carousel_slider: ^4.2.1
  country_pickers: ^2.0.0
  flutter: 
    sdk: flutter
  flutter_riverpod: ^2.1.3
  flutter_svg: ^1.1.6
  flutter_switch: ^0.3.2
  get: ^4.6.6
  intl: ^0.17.0
  pin_code_fields: ^7.3.0
  smooth_page_indicator: ^1.0.0+2
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistSemiBold.ttf
          weight: 600
        - asset: assets/fonts/UrbanistRegular.ttf
          weight: 400
        - asset: assets/fonts/UrbanistRomanRegular.ttf
          weight: 400
