import 'package:banglabeats/core/app_export.dart';import 'package:banglabeats/presentation/downloaded_page/downloaded_page.dart';import 'package:banglabeats/presentation/queue_page/queue_page.dart';import 'package:banglabeats/presentation/your_likes_page/your_likes_page.dart';import 'package:banglabeats/widgets/app_bar/appbar_image.dart';import 'package:banglabeats/widgets/app_bar/appbar_title.dart';import 'package:banglabeats/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class QueueTabContainerScreen extends StatefulWidget {@override _QueueTabContainerScreenState createState() =>  _QueueTabContainerScreenState();
onTapArrowleft27(BuildContext context) { Navigator.pop(context); } 
 }

// ignore_for_file: must_be_immutable
class _QueueTabContainerScreenState extends State<QueueTabContainerScreen> with  TickerProviderStateMixin {late TabController group244Controller;

@override void initState() { super.initState(); group244Controller = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(38), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24), onTap: () {onTapArrowleft27(context);}), title: AppbarTitle(text: "Podcasts", margin: getMargin(left: 16)), actions: [AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgSearch, margin: getMargin(left: 24)), AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgClock28x28, margin: getMargin(left: 20, right: 24))]), body: SizedBox(width: size.width, child: SingleChildScrollView(child: Padding(padding: getPadding(top: 42), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(39), width: double.maxFinite, child: TabBar(controller: group244Controller, labelColor: ColorConstant.redA70002, labelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), unselectedLabelColor: ColorConstant.gray500, unselectedLabelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), indicatorColor: ColorConstant.redA70002, tabs: [Tab(child: Text("Your Likes", overflow: TextOverflow.ellipsis)), Tab(child: Text("Queue", overflow: TextOverflow.ellipsis)), Tab(child: Text("Downloaded", overflow: TextOverflow.ellipsis))])), Container(height: getVerticalSize(797), child: TabBarView(controller: group244Controller, children: [YourLikesPage(), QueuePage(), DownloadedPage()]))])))))); } 
onTapArrowleft27(BuildContext context) { Navigator.pop(context); } 
 }
