import 'package:banglabeats/core/app_export.dart';import 'package:banglabeats/presentation/followers_details_page/followers_details_page.dart';import 'package:banglabeats/widgets/app_bar/appbar_image.dart';import 'package:banglabeats/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class FollowersDetailsTabContainerScreen extends StatefulWidget {@override _FollowersDetailsTabContainerScreenState createState() =>  _FollowersDetailsTabContainerScreenState();
onTapArrowleft22(BuildContext context) { Navigator.pop(context); } 
 }

// ignore_for_file: must_be_immutable
class _FollowersDetailsTabContainerScreenState extends State<FollowersDetailsTabContainerScreen> with  TickerProviderStateMixin {late TabController group44Controller;

@override void initState() { super.initState(); group44Controller = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(50), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24, top: 11, bottom: 11), onTap: () {onTapArrowleft22(context);}), actions: [AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgSearch, margin: getMargin(left: 24, top: 11, right: 11)), AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgClock28x28, margin: getMargin(left: 20, top: 11, right: 35))]), body: Container(width: double.maxFinite, child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(39), width: double.maxFinite, margin: getMargin(top: 25), child: TabBar(controller: group44Controller, labelColor: ColorConstant.redA70002, labelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), unselectedLabelColor: ColorConstant.gray500, unselectedLabelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), indicatorColor: ColorConstant.redA70002, tabs: [Tab(child: Text("Followers", overflow: TextOverflow.ellipsis)), Tab(child: Text("Following", overflow: TextOverflow.ellipsis))])), Container(height: getVerticalSize(767), child: TabBarView(controller: group44Controller, children: [FollowersDetailsPage(), FollowersDetailsPage()]))])))); } 
onTapArrowleft22(BuildContext context) { Navigator.pop(context); } 
 }
