import 'package:banglabeats/core/app_export.dart';import 'package:banglabeats/widgets/app_bar/appbar_image.dart';import 'package:banglabeats/widgets/app_bar/appbar_title.dart';import 'package:banglabeats/widgets/app_bar/custom_app_bar.dart';import 'package:banglabeats/widgets/custom_button.dart';import 'package:banglabeats/widgets/custom_checkbox.dart';import 'package:banglabeats/widgets/custom_text_form_field.dart';import 'package:flutter/material.dart';import 'package:banglabeats/presentation/reset_password_successful_dialog/reset_password_successful_dialog.dart';
// ignore_for_file: must_be_immutable
class CreateNewPasswordScreen extends StatelessWidget {TextEditingController passwordController = TextEditingController();

TextEditingController passwordOneController = TextEditingController();

bool isCheckbox = false;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, resizeToAvoidBottomInset: false, appBar: CustomAppBar(height: getVerticalSize(48), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24, top: 11, bottom: 9), onTap: () {onTapArrowleft6(context);}), title: AppbarTitle(text: "Create New Password", margin: getMargin(left: 16))), body: Container(width: double.maxFinite, padding: getPadding(left: 24, right: 24), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgFrameBlueGray800, height: getVerticalSize(250), width: getHorizontalSize(329), alignment: Alignment.center, margin: getMargin(top: 20)), Padding(padding: getPadding(top: 72), child: Text("Create Your New Password", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistRomanMedium18.copyWith(letterSpacing: getHorizontalSize(0.2)))), CustomTextFormField(focusNode: FocusNode(), controller: passwordController, hintText: "*************", margin: getMargin(top: 25), padding: TextFormFieldPadding.PaddingT21_1, textInputType: TextInputType.visiblePassword, prefix: Container(margin: getMargin(left: 20, top: 20, right: 12, bottom: 20), child: CustomImageView(svgPath: ImageConstant.imgLock20x20)), prefixConstraints: BoxConstraints(maxHeight: getVerticalSize(60)), suffix: Container(margin: getMargin(left: 30, top: 20, right: 20, bottom: 20), child: CustomImageView(svgPath: ImageConstant.imgIconlyBoldHide)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(60)), isObscureText: true), CustomTextFormField(focusNode: FocusNode(), controller: passwordOneController, hintText: "*************", margin: getMargin(top: 24), padding: TextFormFieldPadding.PaddingT21_1, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, prefix: Container(margin: getMargin(left: 20, top: 20, right: 12, bottom: 20), child: CustomImageView(svgPath: ImageConstant.imgLock20x20)), prefixConstraints: BoxConstraints(maxHeight: getVerticalSize(60)), suffix: Container(margin: getMargin(left: 30, top: 20, right: 20, bottom: 20), child: CustomImageView(svgPath: ImageConstant.imgIconlyBoldHide)), suffixConstraints: BoxConstraints(maxHeight: getVerticalSize(60)), isObscureText: true), CustomCheckbox(text: "Remember me", value: isCheckbox, margin: getMargin(top: 24), fontStyle: CheckboxFontStyle.UrbanistSemiBold14Gray900, onChange: (value) {isCheckbox = value;})])), bottomNavigationBar: CustomButton(height: getVerticalSize(55), text: "Continue", margin: getMargin(left: 24, right: 24, bottom: 48), padding: ButtonPadding.PaddingT18, onTap: () {onTapContinue(context);}))); } 
onTapContinue(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: ResetPasswordSuccessfulDialog(),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: EdgeInsets.only(left: 0),)); } 
onTapArrowleft6(BuildContext context) { Navigator.pop(context); } 
 }
