import 'package:banglabeats/core/app_export.dart';import 'package:banglabeats/widgets/app_bar/appbar_image.dart';import 'package:banglabeats/widgets/app_bar/appbar_title.dart';import 'package:banglabeats/widgets/app_bar/custom_app_bar.dart';import 'package:banglabeats/widgets/custom_button.dart';import 'package:banglabeats/widgets/custom_switch.dart';import 'package:flutter/material.dart';
// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable

// ignore_for_file: must_be_immutable
class SecurityScreen extends StatelessWidget {bool isSelectedSwitch = false;

bool isSelectedSwitch1 = false;

bool isSelectedSwitch2 = false;

@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(51), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24, top: 10, bottom: 13), onTap: () {onTapArrowleft41(context);}), title: AppbarTitle(text: "Security", margin: getMargin(left: 16))), body: Container(width: double.maxFinite, padding: getPadding(left: 24, top: 28, right: 24, bottom: 28), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(bottom: 1), child: Text("Remember me", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistSemiBold18Gray80001.copyWith(letterSpacing: getHorizontalSize(0.2)))), CustomSwitch(value: isSelectedSwitch, onChanged: (value) {isSelectedSwitch = value;})]), Padding(padding: getPadding(top: 33), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(top: 1), child: Text("Face ID", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistSemiBold18Gray80001.copyWith(letterSpacing: getHorizontalSize(0.2)))), CustomSwitch(value: isSelectedSwitch1, onChanged: (value) {isSelectedSwitch1 = value;})])), Padding(padding: getPadding(top: 33), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(top: 1), child: Text("Biometric ID", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistSemiBold18Gray80001.copyWith(letterSpacing: getHorizontalSize(0.2)))), CustomSwitch(value: isSelectedSwitch2, onChanged: (value) {isSelectedSwitch2 = value;})])), Padding(padding: getPadding(top: 35), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: getPadding(top: 1), child: Text("Google Authenticator", overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtUrbanistSemiBold18Gray80001.copyWith(letterSpacing: getHorizontalSize(0.2)))), CustomImageView(svgPath: ImageConstant.imgArrowdownRedA70002, height: getSize(20), width: getSize(20), margin: getMargin(bottom: 3))])), CustomButton(height: getVerticalSize(58), text: "Change PIN", margin: getMargin(top: 31), variant: ButtonVariant.OutlineGray80002, padding: ButtonPadding.PaddingAll19, fontStyle: ButtonFontStyle.UrbanistRomanBold16Gray80002_1), CustomButton(height: getVerticalSize(58), text: "Change Password", margin: getMargin(top: 24, bottom: 5), variant: ButtonVariant.OutlineGray80002, padding: ButtonPadding.PaddingAll19, fontStyle: ButtonFontStyle.UrbanistRomanBold16Gray80002_1)])))); } 
onTapArrowleft41(BuildContext context) { Navigator.pop(context); } 
 }
