import 'package:banglabeats/core/app_export.dart';import 'package:banglabeats/presentation/podcasts_notifications_page/podcasts_notifications_page.dart';import 'package:banglabeats/presentation/songs_notifications_page/songs_notifications_page.dart';import 'package:banglabeats/widgets/app_bar/appbar_image.dart';import 'package:banglabeats/widgets/app_bar/appbar_title.dart';import 'package:banglabeats/widgets/app_bar/custom_app_bar.dart';import 'package:flutter/material.dart';class PodcastsNotificationsTabContainerScreen extends StatefulWidget {@override _PodcastsNotificationsTabContainerScreenState createState() =>  _PodcastsNotificationsTabContainerScreenState();
onTapArrowleft7(BuildContext context) { Navigator.pop(context); } 
 }

// ignore_for_file: must_be_immutable
class _PodcastsNotificationsTabContainerScreenState extends State<PodcastsNotificationsTabContainerScreen> with  TickerProviderStateMixin {late TabController group44Controller;

@override void initState() { super.initState(); group44Controller = TabController(length: 2, vsync: this); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(backgroundColor: ColorConstant.whiteA700, appBar: CustomAppBar(height: getVerticalSize(38), leadingWidth: 52, leading: AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgArrowleft, margin: getMargin(left: 24, top: 1), onTap: () {onTapArrowleft7(context);}), title: AppbarTitle(text: "Notifications", margin: getMargin(left: 16)), actions: [AppbarImage(height: getSize(28), width: getSize(28), svgPath: ImageConstant.imgClock28x28, margin: getMargin(left: 24, top: 1, right: 24))]), body: SizedBox(width: size.width, child: SingleChildScrollView(child: Padding(padding: getPadding(top: 42), child: Column(mainAxisAlignment: MainAxisAlignment.start, children: [Container(height: getVerticalSize(39), width: double.maxFinite, child: TabBar(controller: group44Controller, labelColor: ColorConstant.redA70002, labelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), unselectedLabelColor: ColorConstant.gray500, unselectedLabelStyle: TextStyle(fontSize: getFontSize(18), fontFamily: 'Urbanist', fontWeight: FontWeight.w600), indicatorColor: ColorConstant.redA70002, tabs: [Tab(child: Text("Songs", overflow: TextOverflow.ellipsis)), Tab(child: Text("Podcasts", overflow: TextOverflow.ellipsis))])), Container(height: getVerticalSize(847), child: TabBarView(controller: group44Controller, children: [SongsNotificationsPage(), PodcastsNotificationsPage()]))])))))); } 
onTapArrowleft7(BuildContext context) { Navigator.pop(context); } 
 }
